[2024-11-27T08:02:14.542+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_to_vertica.create_table manual__2024-11-27T08:02:13.331266+00:00 [queued]>
[2024-11-27T08:02:14.544+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_to_vertica.create_table manual__2024-11-27T08:02:13.331266+00:00 [queued]>
[2024-11-27T08:02:14.544+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-27T08:02:14.548+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_table> on 2024-11-27 08:02:13.331266+00:00
[2024-11-27T08:02:14.552+0000] {standard_task_runner.py:57} INFO - Started process 421 to run task
[2024-11-27T08:02:14.553+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_data_to_vertica', 'create_table', 'manual__2024-11-27T08:02:13.331266+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/vertica_load_dag.py', '--cfg-path', '/tmp/tmpng6twujv']
[2024-11-27T08:02:14.555+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask create_table
[2024-11-27T08:02:14.583+0000] {task_command.py:415} INFO - Running <TaskInstance: load_data_to_vertica.create_table manual__2024-11-27T08:02:13.331266+00:00 [running]> on host c8f6c342c5cd
[2024-11-27T08:02:14.615+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_to_vertica' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T08:02:13.331266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T08:02:13.331266+00:00'
[2024-11-27T08:02:14.616+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS example_table (
            id INT PRIMARY KEY,
            data VARCHAR(255)
        );
        
[2024-11-27T08:02:14.619+0000] {base.py:73} INFO - Using connection ID 'vertica_conn' for task execution.
[2024-11-27T08:02:14.623+0000] {base.py:73} INFO - Using connection ID 'vertica_conn' for task execution.
[2024-11-27T08:02:14.997+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS example_table (
            id INT PRIMARY KEY,
            data VARCHAR(255)
        );
        , parameters: None
[2024-11-27T08:02:15.138+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:         CREATE TABLE IF NOT EXISTS example_table (
                                           ^

[2024-11-27T08:02:15.154+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=load_data_to_vertica, task_id=create_table, execution_date=20241127T080213, start_date=20241127T080214, end_date=20241127T080215
[2024-11-27T08:02:15.163+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task create_table (permission denied for schema public
LINE 2:         CREATE TABLE IF NOT EXISTS example_table (
                                           ^
; 421)
[2024-11-27T08:02:15.175+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-27T08:02:15.193+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
